services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0.5-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  ml:
    build:
      context: ./karyotypic-analysis/ml_service
      dockerfile: Dockerfile
    command: ["uvicorn", "ml_service.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  celery:
    build:
      context: ./karyotypic-analysis/ml_service
      dockerfile: Dockerfile
    command: ["celery", "-A", "ml_service.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - rabbitmq
