"""Image bytes

Revision ID: 6a8904ca6b6d
Revises: cbd6504d75c8
Create Date: 2025-01-20 17:58:45.689095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8904ca6b6d'
down_revision: Union[str, None] = 'cbd6504d75c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'image_src',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               postgresql_using='image_src::bytea',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'image_src',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               postgresql_using='image_src::varchar',
               existing_nullable=False)
    # ### end Alembic commands ###
